sonar.projectKey=vitaly-zdanevich_bot_telegram_wikimedia_commons
sonar.organization=vitaly-zdanevich
sonar.sources=src
sonar.tests=tests,src
sonar.rust.coverage.reportPaths=coverage/lcov.info
sonar.exclusions=target/**,build/**,.tools/**
