variable "aws_region" {
  type        = string
  description = "AWS region. us-east-1 is close to Wikimedia's Ashburn application datacenter."
  default     = "us-east-1"
}

variable "project_name" {
  type        = string
  description = "Name prefix for AWS resources."
  default     = "telegram-wikimedia-commons-bot"
}

variable "lambda_zip_path" {
  type        = string
  description = "Path to Lambda zip generated by scripts/build-lambda.sh."
  default     = "../build/lambda.zip"
}

variable "telegram_bot_token" {
  type        = string
  description = "Telegram bot token from BotFather. Stored in Terraform state."
  sensitive   = true
}

variable "telegram_webhook_secret" {
  type        = string
  description = "Secret sent by Telegram in X-Telegram-Bot-Api-Secret-Token."
  sensitive   = true
}

variable "admin_telegram_user_ids" {
  type        = string
  description = "Comma-separated Telegram user IDs allowed to use /stat."
  default     = ""
}

variable "github_url" {
  type        = string
  description = "Project URL shown in /help."
  default     = "https://github.com/vitaly-zdanevich/bot_telegram_wikimedia_commons"
}

variable "lambda_memory_size" {
  type        = number
  description = "Lambda memory. 3008 MB is the largest value accepted by this AWS account/region."
  default     = 3008
}

variable "lambda_timeout_seconds" {
  type        = number
  description = "Lambda timeout for Commons download/upload callbacks."
  default     = 300
}

variable "max_file_mb" {
  type        = number
  description = "Maximum Telegram-returnable file size in MB."
  default     = 50
}

variable "stateless_mode" {
  type        = bool
  description = "Disable DynamoDB preferences."
  default     = false
}

variable "enable_test_endpoint" {
  type        = bool
  description = "Enable the authenticated /__test endpoint used by live CI checks."
  default     = true
}

variable "commons_auth_cookie_ssm_parameter" {
  type        = string
  description = "Optional SSM SecureString parameter name containing a Pywikibot LWP cookie jar for authenticated Commons API requests."
  default     = ""

  validation {
    condition     = var.commons_auth_cookie_ssm_parameter == "" || startswith(var.commons_auth_cookie_ssm_parameter, "/")
    error_message = "commons_auth_cookie_ssm_parameter must be empty or an absolute SSM parameter path starting with /."
  }
}

variable "dynamodb_read_capacity" {
  type        = number
  description = "Provisioned DynamoDB RCUs. Keep low to stay in free tier."
  default     = 5
}

variable "dynamodb_write_capacity" {
  type        = number
  description = "Provisioned DynamoDB WCUs. Keep low to stay in free tier."
  default     = 5
}
